version: "3.8"
services:

  api:
    container_name: api
    build: ./
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/todos
    
  db:
    container_name: db 
    image: mongo
    ports: 
      - "27017"